### ISSUE TITLE
drf setup

### ISSUE THREAD

**Issue by climateamante** [climateamante/gitpod.django#1]
- [x] create serializers
- [x] setup views
- [ ] create urls for rest_framework
- [ ] add rest_framework to `settings.py`

**Comment by geekwise-grace-liang** [comment]
@climateamante What is the setup issue?

**Comment by climateamante** [comment]
@geekwise-grace-liang  can you take a look at the `settings.py` file to see what I am missing?
[https://github.com/climateamante/gitpod.django/blob/master/Pipfile](url)

**Comment by geekwise-grace-liang** [comment]
@climateamante Was missing some small typos.

**Comment by climateamante** [comment]
thank you!
